apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-web
  name: nginx-web-service
spec:
  selector:
    app: nginx-web
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
#  type: NodePort
#status:
#  loadBalancer: {}
